#!/usr/bin/env bash

# Build the RSS file
npm run build-rss

# Check if there was any difference that should've been committed
# (should only happen if the pre-commit hook was ignored)
git status --porcelain | grep -zqv 'public/rss.xml' || (echo "update rss.xml with a build" && exit 1)

# Fail the pre-push check if the RSS feed refers to localhost
# Run `npm run build` to generate the production RSS file
grep -zqv 'localhost:3000' public/rss.xml || (echo "update rss.xml with a build" && exit 1)
