import { GitHubRepository } from 'types/github'
import { ProjectInfo } from 'types/projects'

export const sampleRepos: GitHubRepository[] = [
  {
    id: 344686635,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNDQ2ODY2MzU=',
    name: 'json_parser',
    full_name: 'davimiku/json_parser',
    private: false,
    owner: {
      login: 'davimiku',
      id: 36610621,
      node_id: 'MDQ6VXNlcjM2NjEwNjIx',
      avatar_url: 'https://avatars.githubusercontent.com/u/36610621?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/davimiku',
      html_url: 'https://github.com/davimiku',
      followers_url: 'https://api.github.com/users/davimiku/followers',
      following_url:
        'https://api.github.com/users/davimiku/following{/other_user}',
      gists_url: 'https://api.github.com/users/davimiku/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/davimiku/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/davimiku/subscriptions',
      organizations_url: 'https://api.github.com/users/davimiku/orgs',
      repos_url: 'https://api.github.com/users/davimiku/repos',
      events_url: 'https://api.github.com/users/davimiku/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/davimiku/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/davimiku/json_parser',
    description: 'Implementation of a parser for JSON data',
    fork: false,
    url: 'https://api.github.com/repos/davimiku/json_parser',
    created_at: '2021-03-05T03:47:16Z',
    updated_at: '2021-05-05T01:30:17Z',
    pushed_at: '2021-05-05T01:30:15Z',
    homepage: '',
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Rust',
  },
  {
    id: 344686636,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNDQ2ODY2MzU=',
    name: 'AudNauseum',
    full_name: 'AudNauseum/AudNauseum',
    private: false,
    owner: {
      login: 'davimiku',
      id: 36610621,
      node_id: 'MDQ6VXNlcjM2NjEwNjIx',
      avatar_url: 'https://avatars.githubusercontent.com/u/36610621?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/davimiku',
      html_url: 'https://github.com/davimiku',
      followers_url: 'https://api.github.com/users/davimiku/followers',
      following_url:
        'https://api.github.com/users/davimiku/following{/other_user}',
      gists_url: 'https://api.github.com/users/davimiku/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/davimiku/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/davimiku/subscriptions',
      organizations_url: 'https://api.github.com/users/davimiku/orgs',
      repos_url: 'https://api.github.com/users/davimiku/repos',
      events_url: 'https://api.github.com/users/davimiku/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/davimiku/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/AudNauseum/AudNauseum',
    description: 'Code for the AudNauseum program',
    fork: false,
    url: 'https://api.github.com/repos/AudNauseum/AudNauseum',
    created_at: '2021-03-05T03:47:16Z',
    updated_at: '2021-05-05T01:30:17Z',
    pushed_at: '2021-05-05T01:30:15Z',
    homepage: '',
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Python',
  },
  {
    id: 344686635,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNDQ2ODY2MzU=',
    name: 'davimiku.github.io',
    full_name: 'davimiku/davimiku.github.io',
    private: false,
    owner: {
      login: 'davimiku',
      id: 36610621,
      node_id: 'MDQ6VXNlcjM2NjEwNjIx',
      avatar_url: 'https://avatars.githubusercontent.com/u/36610621?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/davimiku',
      html_url: 'https://github.com/davimiku',
      followers_url: 'https://api.github.com/users/davimiku/followers',
      following_url:
        'https://api.github.com/users/davimiku/following{/other_user}',
      gists_url: 'https://api.github.com/users/davimiku/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/davimiku/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/davimiku/subscriptions',
      organizations_url: 'https://api.github.com/users/davimiku/orgs',
      repos_url: 'https://api.github.com/users/davimiku/repos',
      events_url: 'https://api.github.com/users/davimiku/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/davimiku/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/davimiku/davimiku.github.io',
    description: 'Implementation of a parser for JSON data',
    fork: false,
    url: 'https://api.github.com/repos/davimiku/davimiku.github.io',
    created_at: '2021-03-05T03:47:16Z',
    updated_at: '2021-05-05T01:30:17Z',
    pushed_at: '2021-05-05T01:30:15Z',
    homepage: '',
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Typescript',
  },
  {
    id: 344686635,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNDQ2ODY2MzU=',
    name: 'squawker',
    full_name: 'davimiku/squawker',
    private: false,
    owner: {
      login: 'davimiku',
      id: 36610621,
      node_id: 'MDQ6VXNlcjM2NjEwNjIx',
      avatar_url: 'https://avatars.githubusercontent.com/u/36610621?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/davimiku',
      html_url: 'https://github.com/davimiku',
      followers_url: 'https://api.github.com/users/davimiku/followers',
      following_url:
        'https://api.github.com/users/davimiku/following{/other_user}',
      gists_url: 'https://api.github.com/users/davimiku/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/davimiku/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/davimiku/subscriptions',
      organizations_url: 'https://api.github.com/users/davimiku/orgs',
      repos_url: 'https://api.github.com/users/davimiku/repos',
      events_url: 'https://api.github.com/users/davimiku/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/davimiku/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/davimiku/squawker',
    description: 'Implementation of a parser for JSON data',
    fork: false,
    url: 'https://api.github.com/repos/davimiku/squawker',
    created_at: '2021-03-05T03:47:16Z',
    updated_at: '2021-05-05T01:30:17Z',
    pushed_at: '2021-05-05T01:30:15Z',
    homepage: '',
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Python',
  },
]

export const sampleProjects: ProjectInfo[] = [
  {
    tagline: 'Parser for JSON using iterative and combinator strategies',
    technologies: ['Rust'],
    topics: ['parsers', 'combinator parsers', 'json'],
  },
  {
    tagline: 'Loop-based digital recorder/sampler (audio looper)',
    technologies: ['Python', 'PyQt', 'numpy'],
    topics: ['audio processing', 'gui', 'state machine'],
  },
  {
    tagline: 'This website!',
    technologies: ['Typescript', 'Next.js'],
    topics: ['static site generation', 'blog'],
  },
  {
    tagline: 'TODO: replace with Wasteagram',
    technologies: [],
    topics: [],
  },
]

export const sampleData = sampleRepos.map((repo, i) => ({
  repo,
  projectInfo: sampleProjects[i],
}))
